apiVersion: v1
data:
  ANOMALO_DISABLE_HA_CONTROLLERS: "TRUE"
  ANOMALO_GOOGLE_AUTH_CLIENT_ID_SELECTOR: ANOMALO_INTERNAL_APPS
  ANOMALO_IS_INTERNAL: "TRUE"
  ANOMALO_SMTP_HOST: email-smtp.us-west-1.amazonaws.com
  ANOMALO_USE_KRB_AUTH_FOR_SQL_SERVER: "TRUE"
  AWS_DEFAULT_REGION: us-west-1
  AWS_REGION: us-west-1
  DG_BUILD_TAG: joe-test-1
  DG_DEFAULT_S3_BUCKET: joe-anomalo-results
  DG_WEB_ALLOWED_HOSTS: '*'
  DG_WEB_BASE_URL: https://joe-anomalo.sandbox.anomalo.com/
  DG_WEB_CELERY_BROKER_URL: redis://redis:6379/0
  DG_WEB_ENV_NAME: joe-eks
  DG_WEB_LOG_LEVEL: INFO
  DG_WEB_SENTRY_SDK_JS_DSN: https://b62ac698edbe489d88791f661654e8ef@o374026.ingest.sentry.io/4504990920343552
  DG_WEB_SENTRY_SDK_JS_TRACE_SAMPLE_RATE: "0.01"
  DG_WEB_SENTRY_SDK_SERVER_DSN: https://b62ac698edbe489d88791f661654e8ef@o374026.ingest.sentry.io/4504990920343552
  DG_WEB_SENTRY_SDK_SERVER_TRACE_SAMPLE_RATE: "0.01"
  DG_WEB_SERVER_CPU_COUNT: "1"
  DG_WEB_WARM_CACHE_ON_READY: "1"
  DG_WEB_WORKER_CPU_COUNT: "1"
  DJANGO_CSRF_COOKIE_SECURE: "FALSE"
  DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: "FALSE"
  DJANGO_SECURE_HSTS_PRELOAD: "FALSE"
  DJANGO_SECURE_SSL_REDIRECT: "FALSE"
  DJANGO_SESSION_COOKIE_SECURE: "FALSE"
  DJANGO_SETTINGS_MODULE: config.settings.production
  DJANGO_SUPERUSER_EMAIL: super@anomalo.com
  DJANGO_SUPERUSER_FIRST_NAME: Admin
  DJANGO_SUPERUSER_LAST_NAME: User
  DJANGO_SUPERUSER_ORGANIZATION: Anomalo
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: anomalo
    meta.helm.sh/release-namespace: anomalo
  creationTimestamp: "2025-08-29T02:31:08Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: anomalo-env
  namespace: anomalo
  resourceVersion: "232752710"
  uid: 7a6342f9-96fd-43ab-925a-7ddaedffd447
